version: '3.1'

services:
  db:
    container_name: taxi-auth-service
    image: postgres
    restart: always
    environment:
      TZ: 'GMT+5'
      PGTZ: 'GMT+5'
    env_file:
      - .env
    volumes:
      - ./runtime/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
